# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e8467735ceea04b69bcd951439c986381517e2186955a36e7ee760e5e89f2df1fef0dc53a3605bdd62bbfacc8c366baeace33e0ac0b1dbc9f24ba69d51131af

test:
  secret_key_base: f1dc3d5d9420747bc07cb12ab166506483f8543c1eca141eb75ff01276de4e0b778a75996aa89ce4dde26dd7fc26533acfa567210f3d218ea76b357ae190d923

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
